Add Projects section and About me section
medaminedev66/Portfolio pull request #2
Opened 2021-07-08 20:41 UTC by medaminedev66

create two sections:
my-projects section  and About me section
inside my-projects section: Add my-recent-work div and project divs

2021-07-08 22:05 UTC, Georjane requested changes
### Hello, Team @medaminedev66, ✋🏽 

Good job so far! Your PR is professional and you have a good mastery of git-flow. Your linters are all passing, I applaud that too. ✔️ 
However, we have a few more changes to make in order to meet all requirements for this project but you are almost there!

## Required Changes ♻️
- [ ] Kindly follow the button styling: Active, Hover, and Pressed for all buttons on your page ([see Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A468))
- [ ] You are advised to stick to the design as much as possible (e.g., font, colors, images, tests, margins) using the templates in Figma.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a live link of your project to your Readme file. This will enable anyone viewing your repo is easily see your project in action before cloning it.
- Better still, you can as well add an image or screenshot of your project. This increases how professional your Readme appears.

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-08 22:05 UTC, Georjane commented on index.html
> +            <h2>About me</h2>
- [ ] In order to stick to the design as much as possible, you are advised to use the same fonts for this heading and all other sections as it appears in the Figma design

2021-07-09 11:44 UTC, rloterh requested changes
Hi Amine, 

You did great on this project, and for making the changes requested by the previous reviewer!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 

## Good Points 👍  
- No linter errors

## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
__As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).__

2021-07-09 11:44 UTC, rloterh commented on index.html
> +                <button class="see-Project">See Project</button>
Well resolved

2021-07-09 11:44 UTC, rloterh commented on index.html
> +            <h2>About me</h2>
Well resolved

2021-07-09 11:44 UTC, rloterh commented on style.css
> +/* My my-projects */
- [ OPTIONAL] The version of your code on the repository should have no comments in them. This will enhance a cleaner code when there are no comments in your code. Kindly ensure to remove **all** comments in your repository code.

2021-07-09 11:45 UTC, rloterh commented on index.html
> +                </div>
Well resolved

2021-07-09 13:54 UTC, Emmyn5600 approved these changes
## Status: Approved :heavy_check_mark: :muscle::clap:

Hi @medaminedev66 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer. There is nothing else to say other than... it's time to merge it :+1:.
Congratulations! :tada:

## Optional suggestions  
- [ ] Rename your project title as your names not Document.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-09 14:03 UTC, merged